---
title: "Modern approaches to diachronic phonology applied to Basque (MADPAB)"
date: "2021-01-01"
summary: "This project aims to improve our current understanding of Basque historical phonology by incorporating recent advances in theories of phonetically based sound change. We aim to combine the historical-comparative method with phonetic detail and quantitative typological data for studying the historical sound patterns of a language isolate such as Basque, in which the comparative method finds most difficulties. This project will advance our knowledge of general typologies of sound change with a thorough analysis of uncommon changes. The areas of interest cover nasalized /h̃/, stops, sibilants, vowels, and the accentual system. The long-term significance of the project lies in contributing to the reconstruction of the phonology of Proto-Basque as well as to typologies of phonetically based sound change and change in situations of linguistic contact. An indirect major benefit of the project is that it will provide a new methodology for the study of the historical phonologies of isolates."
---

# Modern approaches to diachronic phonology applied to Basque (MADPAB)

**Jan 1, 2021**

Call: ANR-AAPG2020

Duration: Jan 2021 - Dec 2024

This project aims to improve our current understanding of Basque historical phonology by incorporating recent advances in theories of phonetically based sound change. We aim to combine the historical-comparative method with phonetic detail and quantitative typological data for studying the historical sound patterns of a language isolate such as Basque, in which the comparative method finds most difficulties. This project will advance our knowledge of general typologies of sound change with a thorough analysis of uncommon changes. The areas of interest cover nasalized /h̃/, stops, sibilants, vowels, and the accentual system. The long-term significance of the project lies in contributing to the reconstruction of the phonology of Proto-Basque as well as to typologies of phonetically based sound change and change in situations of linguistic contact. An indirect major benefit of the project is that it will provide a new methodology for the study of the historical phonologies of isolates.

---

## Project Members
Click on the <i class = "fas fa-user"></i> next to each project member to visit their personal webpage, <i class = "ai ai-osf ai-lg"></i> for their OSF, <i class = "ai ai-orcid ai-lg"></i> for their ORCID, <i class = "ai ai-google-scholar ai-lg"></i> for their Google Scholar, <i class = "ai ai-researchgate ai-lg"></i> for their ResearchGate, and <i class = "ai ai-academia ai-lg"></i> for their Academia.edu.

#### PI

 * Ander Egurtzegi (CNRS-IKER) [<i class = "fas fa-user"></i>](https://egurtzegi.github.io/) [<i class = "ai ai-osf ai-lg"></i>](https://osf.io/mhdj4/) [<i class = "ai ai-orcid ai-lg"></i>](https://orcid.org/0000-0002-3451-323X/) [<i class = "ai ai-google-scholar ai-lg"></i>](http://scholar.google.com/citations?user=HyhNsDkAAAAJ/) [<i class = "ai ai-researchgate ai-lg"></i>](https://www.researchgate.net/profile/Ander-Egurtzegi/) [<i class = "ai ai-academia ai-lg"></i>](https://cnrs.academia.edu/AnderEgurtzegi/)

#### Research Team

 * Juliette Blevins (CUNY-GC) [<i class = "fas fa-user"></i>](https://julietteblevins.ws.gc.cuny.edu/) [<i class = "ai ai-google-scholar ai-lg"></i>](https://scholar.google.com/citations?user=CBEWVrEAAAAJ/)

 * Christopher Carignan (UCL) [<i class = "fas fa-user"></i>](https://www.christophercarignan.com/) [<i class = "ai ai-osf ai-lg"></i>](https://osf.io/5ucv8/) [<i class = "ai ai-orcid ai-lg"></i>](https://orcid.org/0000-0002-1565-3691/) [<i class = "ai ai-google-scholar ai-lg"></i>](https://scholar.google.com/citations?user=naAMMOwAAAAJ/) [<i class = "ai ai-researchgate ai-lg"></i>](https://www.researchgate.net/profile/Christopher-Carignan/)

 * Gorka Elordieta (UPV/EHU) [<i class = "fas fa-user"></i>](https://hittlinguistics.wixsite.com/hitt/gorka-elordieta/) [<i class = "ai ai-orcid ai-lg"></i>](https://orcid.org/0000-0003-1235-6998/) [<i class = "ai ai-google-scholar ai-lg"></i>](https://scholar.google.com/citations?user=qMSZUasAAAAJ/) [<i class = "ai ai-researchgate ai-lg"></i>](https://www.researchgate.net/profile/Gorka-Elordieta/) [<i class = "ai ai-academia ai-lg"></i>](https://cnrs.academia.edu/GorkaElordieta/)

 * Dorota Krajewska (UPV/EHU) [<i class = "ai ai-osf ai-lg"></i>](https://osf.io/2c7j8/) [<i class = "ai ai-orcid ai-lg"></i>](https://orcid.org/0000-0002-6909-985X/) [<i class = "ai ai-google-scholar ai-lg"></i>](https://scholar.google.com/citations?user=N1fwk4IAAAAJ/) [<i class = "ai ai-researchgate ai-lg"></i>](https://www.researchgate.net/profile/Dorota-Krajewska/)

 * Iñigo Urrestarazu-Porta (CNRS-IKER, UPPA & UPV/EHU) [<i class = "ai ai-researchgate ai-lg"></i>](https://www.researchgate.net/profile/Inigo-Urrestarazu-Porta/)

 * Andrea García-Covelo (IPS-LMU, CNRS-IKER & UPPA)

---

## Project Publications
 * Egurtzegi, A. & G. Elordieta. 2023 [online 2022]. A history of the Basque prosodic systems. _Diachronica_ 40.1, 30-72. [<i class = "ai ai-doi ai-lg"></i>](http://doi.org/10.1075/dia.20066.egu) [<i class = "ai ai-open-access ai-lg"></i>](https://www.jbe-platform.com/content/journals/10.1075/dia.20066.egu)

 * Blevins, J. & A. Egurtzegi. 2023 [online 2022]. Refining explanation in Evolutionary Phonology: Macro-typologies and targeted typologies in action. _Linguistic Typology_ 27.2, 289-311. [<i class = "ai ai-doi ai-lg"></i>](https://doi.org/10.1515/lingty-2021-0036) [<i class = "ai ai-open-access ai-lg"></i>](https://www.degruyter.com/document/doi/10.1515/lingty-2021-0036)

 * Krajewska, D., E. Zuloaga & A. Egurtzegi. 2022. Sibilant mergers in 18th-century Basque: A quantitative study. _Phonological Data & Analysis_ 4.5, 1–31. [<i class = "ai ai-doi ai-lg"></i>](https://doi.org/10.3765/pda.v4art5.67) [<i class = "ai ai-open-access ai-lg"></i>](https://phondata.org/index.php/pda/article/view/67/43) [<i class = "ai ai-osf ai-lg"></i>](https://osf.io/t6a7w/)

 * Egurtzegi, A. 2022. Goizuetako azentueraren garapena kokatzen Euskara Batu Zaharraren prosodia zehazteko: proposamenen ebaluazioa. [Placing the development of the Goizueta prosodic system to define the prosody of Common Basque: Evaluation of the proposals]. _Fontes Linguae Vasconum_ 133, 9–35. [<i class = "ai ai-doi ai-lg"></i>](https://doi.org/10.35462/flv133.1) [<i class = "ai ai-open-access ai-lg"></i>](https://www.culturanavarra.es/uploads/files/FLV133_01.pdf)

 * Elordieta, G. & A. Egurtzegi. 2022. Bizkaiko iparraldeko euskararen doinu-azentuaren berrikusketa [A revision of the pitch accent of Northern Bizkaian Basque]. In Barberia & Iribar (eds.), _Papers on Basque Linguistics in Honor of Jon Andoni Franco Elorza_. Bilbao: Deusto University Press, 319-337. [<i class = "ai ai-open-access ai-lg"></i>](../../publications/elordieta-egurtzegi-2022-bizkaiko-doinu-azentuaren/)

---

## Organized Conferences & Workshops
 * [Understanding sound change](https://understandingsoundchange.netlify.app/)

 Workshop held at Donostia/San Sebastián (27/01/2022), part of OCP-19.

 * [19th Old World Conference on Phonology](https://sulfsbjorninn.wixsite.com/ocp19/)

 Conference held at Donostia/San Sebastián (26/01/2022-28/01/2022).

---

## Invited Talks & Conference Contributions
1.  Egurtzegi, A. 2021. "Sibilant contrasts and sibilant merger in Mixean Basque". Lancaster Phonetics Laboratory (U. of Lancaster, UK).
2.  Egurtzegi, A. 2021. "Reconstructing Proto-Basque prosody and the development of the modern Basque prosodic diversity". Séminaire CLLE-ERSSàB (Université Bordeaux Montaigne, France).
3.  Egurtzegi, A. 2021. "Final obstruent voicing in Lakota: Phonetic evidence and phonological implications". Séminaires de Recherches en Phonétique et Phonologie (U. Sorbonne Nouvelle, Paris, France).
4.  Elordieta, G. & A. Egurtzegi. 2021. "Lexical and non-lexical tones in Northern Bizkaian Basque". UD Workshop on Basque Linguistics (University of Deusto, Spain).
5.  Elordieta, G. & A. Egurtzegi. 2022. "Lexical and non-lexical tones in Basque revisited". OCP-19 (University of Deusto, Spain).
6.  Zuloaga, E. & D. Krajewska. 2022. "Sociohistorical explanations for sibilant mergers in Basque", 11th Historical Sociolinguistics Network Conference (University of Murcia, Spain).
7.  Elordieta, G. & A. Egurtzegi. 2022. "A new proposal for the tonal representation of phonological phrases in Northern Bizkaian Basque". 31st Colloquium of Generative Grammar (University of the Balearic Islands, Spain).
8.  Egurtzegi , A., J. Cronenberg, M. Gubian, J. Harrington & H. Ruch. 2022. "From post-lexicality to phonologization: Andalusian /s/-aspiration at the word boundary". LabPhon18 (held online due to COVID-19).
9.  Egurtzegi , A., J. Cronenberg, M. Gubian, J. Harrington & H. Ruch. 2022. "La aspiración de /s/ en andaluz: el largo camino de la post-lexicalidad a la lexicalización". Congrès International de Linguistique et de Philologie Romanes 30 (University of La Laguna, Spain).
10. Krajewska, D., E. Zuloaga & A. Egurtzegi. 2022. "A quantitative analysis of sibilant mergers in 18th-century Basque". International Conference on Historical Linguistics 25 (University of Oxford, UK).
11. Egurtzegi, A. & G. Elordieta. 2022. "A history of the Basque prosodic systems". International Conference on Historical Linguistics 25 (University of Oxford, UK).
12. Egurtzegi, A. 2022 "Phonological features conditioned by contact with Gascon in Zuberoan Basque". Basque Summer Tutorial in Language Documentation (U. Bordeaux-Montaigne & Uni Konstanz, Larraine, France).
13. Egurtzegi, A. 2022. "When time is the key: Analyzing time-varying data in laboratory phonology". LPRG - Laboratory Phonology Research Group (Université Paris Cité, Paris, France).
14. Egurtzegi, A. 2022. "Andalusian pre-to-post-aspiration and the life cycle of sound change". Workshop on Sound Change. Departamento de Lengua Española y Lingüística General (UNED, Madrid, Spain).
15. Egurtzegi, A., A. García-Covelo & I. Urrestarazu-Porta. 2023. "Endangered language documentation: A nasalance-based study of the /h/ vs. /h̃/ opposition in Zuberoan Basque". Linguistics MA program (University of the Basque Country, Vitoria-Gasteiz, Spain).
16. Egurtzegi, A., J. Cronenberg & J. Harrington. 2023. "Andalusian aspiration as a path into sound change research". Linguistics MA program (University of the Basque Country, Vitoria-Gasteiz, Spain).
17. Egurtzegi, A., J. Cronenberg & J. Harrington. 2023. "La variación intergeneracional como reflejo del cambio en curso: La post-aspiración de /s/ + oclusiva en andaluz". Linguistic Variation Talk Series (Universidad Autónoma de Madrid, Spain).
18. Egurtzegi, A., A. García-Covelo & I. Urrestarazu-Porta. 2023. "A LabPhon account of Basque /h̃/". CLT Seminars (Universitat Autònoma de Barcelona, Spain).
19. Zuloaga, E., D. Krajewska & A. Egurtzegi. 2023. "Textual genres and linguistic variation: Socio-historical explanations for Basque sibilant mergers". Historical Sociolinguistics Network Conference (HiSoN-12) (Vrije Universiteit Brussel, Belgium).
20. Egurtzegi, A., A. García-Covelo & I. Urrestarazu-Porta. 2023. Documenting nasalized aspirates in Zuberoan Basque. 9th International Conference on Experimental Phonetics (CIFE; University of Vigo, Spain).
21. Egurtzegi, A., D. Krajewska, C. Carignan & I. Urrestarazu-Porta. 2023. "An acoustic description of sibilant contrasts and sibilant merger in Mixean Basque". CIFE 9 (University of Vigo, Spain).
22. Egurtzegi, A. 2023. "An 'impossible' opposition: /h/ vs. /h̃/ in North-Eastern Basque". 53rd Linguistic Symposium on Romance Languages (LSRL 53), Phonetics and phonology – Beyond Romance (Paris, France).
23. Egurtzegi, A., A. García-Covelo & I. Urrestarazu-Porta. 2023. "A nasalance-based study of the /h/ vs. /h̃/ opposition in Zuberoan Basque". 20th International Congress of Phonetic Sciences (ICPhS, Prague). 