---
title: "Mixean Basque"
date: "2017-01-01"
summary: "This project involves the phonetic description of Mixean Low Navarrese, an endangered variety of Basque. Preceding the acoustic analysis of this variety, we compile an overview of all previous acoustic studies performed on different Basque varieties, in order to synthesize the sparse acoustic descriptions of the language that are available. This synthesis serves as a basis for the acoustic analysis performed in the current study, in which we replicate the various acoustic descriptions given in previous studies in a single, cohesive general acoustic description of Mixean Basque. The analyses include formant and duration measurements for the six-vowel system, voice onset time measurements for the three-way stop system, spectral center of gravity for the sibilants, and number of lingual contacts in the alveolar rhotic tap and trill. Important findings include: a centralized realization ([ʉ]) of the high-front rounded vowel usually described as /y/; a data-driven confirmation of the three-way laryngeal opposition in the stop system; evidence in support of an alveolo-palatal to apical sibilant merger; and the discovery of a possible incipient merger of rhotics. These results show how using experimental acoustic methods to study under-represented linguistic varieties can result in revelations of sound patterns otherwise undescribed in more commonly studied varieties."
---

# Mixean Basque

**Jan 1, 2017**

This project involves the phonetic description of Mixean Low Navarrese, an endangered variety of Basque. Preceding the acoustic analysis of this variety, we compile an overview of all previous acoustic studies performed on different Basque varieties, in order to synthesize the sparse acoustic descriptions of the language that are available. This synthesis serves as a basis for the acoustic analysis performed in the current study, in which we replicate the various acoustic descriptions given in previous studies in a single, cohesive general acoustic description of Mixean Basque. The analyses include formant and duration measurements for the six-vowel system, voice onset time measurements for the three-way stop system, spectral center of gravity for the sibilants, and number of lingual contacts in the alveolar rhotic tap and trill. Important findings include: a centralized realization ([ʉ]) of the high-front rounded vowel usually described as /y/; a data-driven confirmation of the three-way laryngeal opposition in the stop system; evidence in support of an alveolo-palatal to apical sibilant merger; and the discovery of a possible incipient merger of rhotics. These results show how using experimental acoustic methods to study under-represented linguistic varieties can result in revelations of sound patterns otherwise undescribed in more commonly studied varieties.

---

## Project Members

 * Ander Egurtzegi (CNRS-IKER)
   <div class="touch-aware-links">
     <a href="https://egurtzegi.github.io/" class="website-link"><i class="fas fa-user"></i><span class="link-text">Website</span></a>
     <a href="https://osf.io/mhdj4/" class="osf-link"><i class="ai ai-osf"></i><span class="link-text">OSF</span></a>
     <a href="https://orcid.org/0000-0002-3451-323X/" class="orcid-link"><i class="ai ai-orcid"></i><span class="link-text">ORCID</span></a>
     <a href="http://scholar.google.com/citations?user=HyhNsDkAAAAJ/" class="scholar-link"><i class="ai ai-google-scholar"></i><span class="link-text">Scholar</span></a>
     <a href="https://www.researchgate.net/profile/Ander-Egurtzegi/" class="researchgate-link"><i class="ai ai-researchgate"></i><span class="link-text">ResearchGate</span></a>
     <a href="https://cnrs.academia.edu/AnderEgurtzegi/" class="academia-link"><i class="ai ai-academia"></i><span class="link-text">Academia</span></a>
   </div>

 * Christopher Carignan (UCL)
   <div class="touch-aware-links">
     <a href="https://www.christophercarignan.com/" class="website-link"><i class="fas fa-user"></i><span class="link-text">Website</span></a>
     <a href="https://osf.io/5ucv8/" class="osf-link"><i class="ai ai-osf"></i><span class="link-text">OSF</span></a>
     <a href="https://orcid.org/0000-0002-1565-3691/" class="orcid-link"><i class="ai ai-orcid"></i><span class="link-text">ORCID</span></a>
     <a href="https://scholar.google.com/citations?user=naAMMOwAAAAJ/" class="scholar-link"><i class="ai ai-google-scholar"></i><span class="link-text">Scholar</span></a>
     <a href="https://www.researchgate.net/profile/Christopher-Carignan/" class="researchgate-link"><i class="ai ai-researchgate"></i><span class="link-text">ResearchGate</span></a>
   </div>

 * Dorota Krajewska (UPV/EHU)
   <div class="touch-aware-links">
     <a href="https://orcid.org/0000-0002-6909-985X/" class="orcid-link"><i class="ai ai-orcid"></i><span class="link-text">ORCID</span></a>
     <a href="https://scholar.google.com/citations?user=N1fwk4IAAAAJ/" class="scholar-link"><i class="ai ai-google-scholar"></i><span class="link-text">Scholar</span></a>
     <a href="https://www.researchgate.net/profile/Dorota-Krajewska/" class="researchgate-link"><i class="ai ai-researchgate"></i><span class="link-text">ResearchGate</span></a>
   </div>

 * Iñigo Urrestarazu-Porta (CNRS-IKER, UPPA & UPV/EHU)
   <div class="touch-aware-links">
     <a href="https://www.researchgate.net/profile/Inigo-Urrestarazu-Porta/" class="researchgate-link"><i class="ai ai-researchgate"></i><span class="link-text">ResearchGate</span></a>
   </div>

---

## Project Publications
 * 2020 [with C. Carignan] An acoustic description of Mixean Basque. _Journal of the Acoustical Society of America_ 147.4, 2791–2802.
  <div class="touch-aware-links">
    <a href="https://doi.org/10.1121/10.0000996" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="https://asa.scitation.org/doi/pdf/10.1121/10.0000996" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
    <a href="https://asa.scitation.org/doi/suppl/10.1121/10.0000996/suppl_file/supppub1.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">Supplement</span></a>
  </div>

---

## Invited Talks & Conference Contributions
1.  Egurtzegi, A. 2017. "Sporadic nasalization of /h/: the loss of a rare contrast in Mixean Basque". 4th International Workshop on Sound Change (University of Edinburgh, UK).
2.  Egurtzegi, A. 2017. "The loss of a typologically rare opposition in two endangered dialects: /h/ vs. /h̃/ in Mixean and Zuberoan Basque". ICHL 23 (University of Texas San Antonio, USA).
3.  Egurtzegi, A. & C. Carignan. 2019.  "Amiküzeraren deskribapen akustikoa" [Acoustic description of Mixean Basque]. MLV5en 3. mintegia (University of the Basque Country, Vitoria-Gasteiz, Spain).
4.  Egurtzegi, A. & C. Carignan. 2019.  "A case of perceptual reanalysis: The ongoing merger of /h/ and /h̃/ in Mixean Basque". Whither reanalysis? (Humboldt University Berlin).
5.  Egurtzegi, A. & C. Carignan. 2020.  "Rhinoglottophilia is alive and well in Mixean Basque". LabPhon17 (University of British Columbia, Vancouver, Canada [held online due to COVID-19]).
6.  Egurtzegi, A. & D. Krajewska. 2021. "Sibilant contrasts and sibilant merger in Mixean Basque". Lancaster Phonetics Laboratory (U. of Lancaster, UK).
7.  Egurtzegi, A., D. Krajewska, C. Carignan & I. Urrestarazu-Porta. 2023. "An acoustic description of sibilant contrasts and sibilant merger in Mixean Basque". 9th International Conference on Experimental Phonetics (CIFE; University of Vigo, Spain). 