---
title: "Publications"
page-layout: custom
---

<div class="grid">
<div class="g-col-12">

# Publications

In all papers, the open-access icon <i class="ai ai-open-access ai-lg"></i> links to a freely accessible pdf. The DOI icon <i class="ai ai-doi ai-lg"></i> links to the DOI or paper webpage (whenever available) and the arXiv icon <i class="ai ai-arxiv ai-lg"></i> links to arXiv. <i class="fab fa-github"></i> links to the Github repo and <i class="ai ai-osf ai-lg"></i> to the OSF repo (code + extra materials).

<hr/>

## Journal Publications

- 2024 [with D. Krajewska, C. Carignan & I. Urrestarazu-Porta] An acoustic exploration of sibilant contrasts and sibilant merger in Mixean Basque. *Journal of the International Phonetic Association* 54.2, 677-706.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.1017/S0025100324000045" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="https://www.cambridge.org/core/services/aop-cambridge-core/content/view/839C776F241162A02D7505FE4D042A7E/S0025100324000045a.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
    <a href="https://osf.io/vctgw/" class="osf-link"><i class="ai ai-osf"></i><span class="link-text">OSF</span></a>
  </div>
- 2024 [with I. Urrestarazu-Porta & A. García-Covelo] Sudurkaritasun fonologikoa Larrainen: /h̃/ bai, baina bokalik ez [Phonological nasality in Larraine Basque: there is /h̃/, but no nasal vowels]. *Fontes Linguae Vasconum* 137, 163-190.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.35462/flv137.7" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="https://www.culturanavarra.es/uploads/files/FLV137-07.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2023 [with J. Blevins] Refining explanation in Evolutionary Phonology: Macro-typologies and targeted typologies in action. *Linguistic Typology* 27.2, 289-311.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.1515/lingty-2021-0036" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="https://www.degruyter.com/document/doi/10.1515/lingty-2021-0036" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2023 [with G. Elordieta] A history of the Basque prosodic systems. *Diachronica* 40.1, 30-72.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.1075/dia.20066.egu" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="https://www.jbe-platform.com/content/journals/10.1075/dia.20066.egu" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2023 [with S. Coretta, J. Casillas, [...] & T. Roettger] Multidimensional signals and analytic flexibility: Estimating degrees of freedom in human speech analyses. *Advances in Methods and Practices in Psychological Science* 6.3.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.1177/25152459231162567" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="https://journals.sagepub.com/doi/full/10.1177/25152459231162567" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
    <a href="https://github.com/many-speech-analyses/many_analyses" class="github-link"><i class="fab fa-github"></i><span class="link-text">GitHub</span></a>
    <a href="https://osf.io/3bmcp/" class="osf-link"><i class="ai ai-osf"></i><span class="link-text">OSF</span></a>
    <a href="https://osf.io/g9bq5/" class="osf-link"><i class="ai ai-osf"></i><span class="link-text">OSF</span></a>
  </div>
- 2023 /h̃/ hasperen sudurkarituaren inguruan. *International Journal of Basque Linguistics and Philology (ASJU)* 57, 275-294.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.1387/asju.25952" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="https://ojs.ehu.eus/index.php/ASJU/article/view/25952/24923" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2022 [with D. Krajewska & E. Zuloaga] Sibilant mergers in 18th-century Basque: A quantitative study. *Phonological Data & Analysis* 4.5, 1-31.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.3765/pda.v4art5.67" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="https://phondata.org/index.php/pda/article/view/67/43" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
    <a href="https://osf.io/t6a7w/" class="osf-link"><i class="ai ai-osf"></i><span class="link-text">OSF</span></a>
  </div>
- 2022 Goizuetako azentueraren garapena kokatzen Euskara Batu Zaharraren prosodia zehazteko: proposamenen ebaluazioa [Placing the development of the Goizueta prosodic system to define the prosody of Common Basque: Evaluation of the proposals]. *Fontes Linguae Vasconum* 133, 9-35.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.35462/flv133.1" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="https://www.culturanavarra.es/uploads/files/FLV133_01.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2020 [with J. Blevins & J. Ullrich] Final obstruent voicing in Lakota: Phonetic evidence and phonological implications. *Language* 96.2, 294-337.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.1353/lan.2020.0022" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="/static/files/Blevinsetal2020Reduced.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2020 [with C. Carignan] An acoustic description of Mixean Basque. *Journal of the Acoustical Society of America* 147.4, 2791-2802.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.1121/10.0000996" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="https://asa.scitation.org/doi/pdf/10.1121/10.0000996" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
    <a href="https://asa.scitation.org/doi/suppl/10.1121/10.0000996/suppl_file/supppub1.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">Supplement</span></a>
    <a href="https://osf.io/s2qxj/" class="osf-link"><i class="ai ai-osf"></i><span class="link-text">OSF</span></a>
  </div>
- 2019 Metathesis of aspiration as the source of anticipatory voicelessness in Basque. *Journal of French Language Studies* 29.2, 265-279.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.1017/S0959269518000339" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="https://www.cambridge.org/core/services/aop-cambridge-core/content/view/6AFAF84FE1A5D486CAADEE6555986E8C/S0959269518000339a.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2018 On the phonemic status of nasalized /h̃/ in Modern Zuberoan Basque. *Linguistics* 56.6, 1353-1367.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.1515/ling-2018-0024" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="/static/files/Egurtzegi-2018-Linguistics.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2018 [with I. San Martin] Morfema mugetako hots aldaketak Zaldibarko euskaran: Azterketa akustikoa [Morpheme-boundary sound changes in Zaldibar Basque: Acoustic study]. *Lapurdum* 21.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.4000/lapurdum.3697" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="https://journals.openedition.org/lapurdum/3697" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
    <a href="/static/files/lapurdum-3697.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
    <a href="/static/files/Zaldibar_10-07_Azkena.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">Preprint</span></a>
  </div>
- 2018 Herskarien ustezko ahoskabetasun asimilazioa eta euskal herskari zaharren gauzatzea [The alleged voicelessness assimilation and the realization of Old Basque stops]. *International Journal of Basque Linguistics and Philology (ASJU)* 52, 189-206.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.1387/asju.20198" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="http://www.ehu.eus/ojs/index.php/ASJU/article/view/20198/18324" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2017 [with J. Blevins] Unexpected obstruent loss in initial obstruent-sonorant clusters: An apparent example from Basque. *Phonology* 34.3, 507-522.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.1017/S0952675717000264" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="/static/files/blevins_egurtzegi2017phonology.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2017 Phonetically conditioned sound change: Contact induced /u/-fronting in Zuberoan Basque. *Diachronica* 34.3, 331-367.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.1075/dia.34.3.02egu" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="/static/files/Egurtzegi-u-fronting-preprint.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2015 Different distributions of contrastive vowel nasalization in Basque. *Loquens: Spanish Journal of Speech Sciences* 2.1, e017.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.3989/loquens.2015.017" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="https://loquens.revistas.csic.es/index.php/loquens/article/view/22/63" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2013 [2018] Ekialdeko /o/-ren igoeraren testuinguru fonologikoaren bila [Looking for the phonological context of /o/-raising in Eastern Basque]. *International Journal of Basque Linguistics and Philology (ASJU)* 48.2, 257-266.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.1387/asju.18683" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="http://www.ehu.eus/ojs/index.php/ASJU/article/view/18683/17582" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2013 [with B. Ariztimuño] Remarks on the etymology of the Basque word for 'swallow' and its potential relation to Celtic. *Ériu* 63, 79-90.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.3318/ERIU.2013.63.79" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="/static/files/Egurtzegi&Ariztimuno2013Swallows.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2012 Hugo Ernst Schuchardt: Bibliografía vasca [Hugo Ernst Schuchardt: Basque Bibliography]. *International Journal of Basque Linguistics and Philology (ASJU)* 46, 161-176.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.1387/asju.13450" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="https://www.ehu.eus/ojs/index.php/ASJU/article/view/13450/12044" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2011 Euskal metatesiak: Abiaburua haien ikerketarako [Basque metatheses: starting point for their research]. *International Journal of Basque Linguistics and Philology (ASJU)* 45, 1-79.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.1387/asju.9725" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="http://www.ehu.eus/ojs/index.php/ASJU/article/view/9725/8965" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2011 [with B. Ariztimuño] Enarak, elaiak eta testuinguruaren garrantzia [Enarak, elaiak [swallows] and the importance of the context]. *International Journal of Basque Linguistics and Philology (ASJU)* 45, 403-410.
  <div class="touch-aware-links compact">
    <a href="https://doi.org/10.1387/asju.9747" class="doi-link"><i class="ai ai-doi"></i><span class="link-text">DOI</span></a>
    <a href="http://www.ehu.eus/ojs/index.php/ASJU/article/view/9747/8987" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2009 [with M. Ayerbe] La formación del plural en alemán desde una perspectiva morfofonológica [The development of the German plural from a morpho-phonological perspective]. *Estudios Filológicos Alemanes* 19, 237-268.

## Book Chapters

- 2026 (In press) Metathesis. In Ledgeway et al. (eds.), *The Wiley Blackwell Companion to Diachronic Linguistics*. Wiley-Blackwell.
  <div class="touch-aware-links compact">
    <a href="/static/files/MetathesisDiaComEgurtzegi.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2022 [with G. Elordieta] Bizkaiko iparraldeko euskararen doinu-azentuaren berrikusketa [A revision of the pitch accent of Northern Bizkaian Basque]. In Barberia & Iribar (eds.), *Papers on Basque Linguistics in Honor of Jon Andoni Franco Elorza*, 319-337. Deusto University Press.
  <div class="touch-aware-links compact">
    <a href="/static/files/Elordieta-Egurtzegi-2022.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2019 [with B. Ariztimuño] /f/-ren sarrera eta sorrera euskaran [Introduction and inception of /f/ in Basque]. In Epelde & Jauregi (eds.), *Bihotz ahots. M.L. Oñederra irakaslearen omenez*, 197-213. UPV/EHU.
  <div class="touch-aware-links compact">
    <a href="/static/files/EgurtzegiAriztimuno2019.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2018 Nasalized mid back vowel raising in Gascon and Basque. In Recasens & Sáchez-Miret (eds.), *Production and perception mechanisms of sound change*, 173-187. Lincom.
  <div class="touch-aware-links compact">
    <a href="/static/files/Egurtzegi2018Nasalized-o-raising.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2015 Zubereraren /y/: Bere sorrera eta hedapenaren inguruan [Zuberoan /y/: On its creation and spread]. In Ezeizabarrena & Gómez (eds.) *Eridenen du zerzaz kontenta*, 149-162. UPV/EHU.
  <div class="touch-aware-links compact">
    <a href="/static/files/Egurtzegi2015.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2013 Phonetics and Phonology. In Martínez-Areta (ed.), *Basque and Proto-Basque. Language-Internal and typological approaches to linguistic reconstruction*, 119-172. Peter Lang.
  <div class="touch-aware-links compact">
    <a href="/static/files/Egurtzegi-2013-Phonetics&Phonology.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2013 Diferentes tipos de aspiración en vasco (con análisis espectrales del dialecto suletino actual) [Different kinds of aspiration in Basque (with spectral analyses of the modern Zuberoan dialect)]. In Blasco et al. (eds.), *Iberia e Sardegna*, 151-169. Le Monnier.
  <div class="touch-aware-links compact">
    <a href="/static/files/Egurtzegi-SardiniaProofs.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>

## Refereed Conference Publications

- 2023 [with A. García-Covelo & I. Urrestarazu-Porta] A nasalance-based study of the /h/ vs. /h̃/ opposition in Zuberoan Basque. In Radek Skarnitzl & Jan Volín (ed.), *Proceedings of the 20th International Congress of Phonetic Sciences*, 3427-3431. Guarant International.
  <div class="touch-aware-links compact">
    <a href="https://www.internationalphoneticassociation.org/icphs-proceedings/ICPhS2023/full_papers/1047.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2015 [õ] sudurkarituaren igoera ekialdeko euskalkietan [Raising of nasalized [õ] in the eastern Basque dialects]. *Ikergazte: International research in Basque* 39-45. UEU.
- 2013 [with G. Elordieta] Euskal azentueren historiaz [On the history of Basque accentuation.]. In Gómez et al. (eds.), *3rd Conference of the Luis Michelena Chair*, 163-186. UPV/EHU.
  <div class="touch-aware-links compact">
    <a href="/static/files/Egurtzegi & Elordieta 2013-KMK III.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>

## Outreach publications

- 2018 Can speech errors become part of a language?. *Berichte* 2017, 10-13.
  <div class="touch-aware-links compact">
    <a href="/static/files/EgurtzegiIBZBerichte2017.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>

## Other publications

- 2021 [with C. Carignan] Principal components variable importance reconstruction (PC-VIR): Exploring predictive importance in multicollinear acoustic speech data.
  <div class="touch-aware-links compact">
    <a href="https://arxiv.org/pdf/2102.04740.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
    <a href="https://arxiv.org/abs/2102.04740" class="doi-link"><i class="ai ai-arxiv"></i><span class="link-text">arXiv</span></a>
    <a href="https://github.com/ChristopherCarignan/PC-VIR" class="github-link"><i class="fab fa-github"></i><span class="link-text">GitHub</span></a>
  </div>
- 2021 [with G. Elordieta, O. Jauregi, D. Krajewska, M.L. Oñederra & I. Urrestarazu] Nazioarteko Alfabeto Fonetikoa (2021ean moldatua) [Basque translation of The International Phonetic Alphabet].
  <div class="touch-aware-links compact">
    <a href="/static/files/IPA_Kiel_2021_full_eus.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>
- 2014 Towards a phonetically grounded diachronic phonology of Basque [PhD dissertation].
  <div class="touch-aware-links compact">
    <a href="/static/files/Egurtzegi2014.pdf" class="pdf-link"><i class="ai ai-open-access"></i><span class="link-text">PDF</span></a>
  </div>

</div>
</div>